/*
Author: ≈∑—Ùœ»Œ∞(Xianwei Ouyang)
Version 0.1.2, 2007/04/15
allskystar@hotmail.com
*/
var s = HTMLWindows.defaultStyles;
s.set("#control", "background-color:#D4D0C8;");
s.set("#control #outline", "border-top:1px solid #808080;border-left:1px solid #808080;border-right:1px solid #FFF;border-bottom:1px solid #FFF;");
s.set("#control #inline", "border-top:1px solid #FFF;border-left:1px solid #FFF;border-right:1px solid #808080;border-bottom:1px solid #808080;");
s.set("#down", "background-color:#D4D0C8;");
s.set("#down #outline", "border-top:1px solid #808080;border-left:1px solid #808080;border-right:1px solid #FFF;border-bottom:1px solid #FFF;");
s.set("#up", "background-color:#D4D0C8;");
s.set("#up #outline", "border-top:1px solid #FFF;border-left:1px solid #FFF;border-right:1px solid #808080;border-bottom:1px solid #808080;");
s.set("#sdown", "background-color:#D4D0C8;");
s.set("#sdown #outline", "border-top:1px solid #404040;border-left:1px solid #404040;border-right:1px solid #FFF;border-bottom:1px solid #FFF;");
s.set("#sdown #inline", "border-top:1px solid #808080;border-left:1px solid #808080;border-right:1px solid #D4D0C8;border-bottom:1px solid #D4D0C8;");
s.set("#sup", "background-color:#D4D0C8;");
s.set("#sup #outline", "border-top:1px solid #FFF;border-left:1px solid #FFF;border-right:1px solid #404040;border-bottom:1px solid #404040;");
s.set("#sup #inline", "border-top:1px solid #D4D0C8;border-left:1px solid #D4D0C8;border-right:1px solid #808080;border-bottom:1px solid #808080;");
s.set("#scroll", "background-image:url(" + wsclPath + "skins/windows/scroll.bmp);z-index:" + HTMLComponent.prototype.UNSIGNED + ";");
s.set("#scroll #block .sup", "");
s.set("#scroll #block #outline", "border-top:1px solid #D4D0C8;border-left:1px solid #D4D0C8;");
s.set("#scroll #block #inline", "border-top:1px solid #FFF;border-left:1px solid #FFF;");
s.set("#scroll #button .scroll #block", "");
s.set("#scroll #button #icon", "top:0;left:0");
s.set("#scroll #button #press #outline", "border:1px solid #808080;");
s.set("#scroll #button #press #inline", "border:1px solid #D4D0C8;");
s.set("#scroll #button #press #icon", "top:1px;left:1px;");
s.set("#vscroll .scroll", "width:16px;top:0px;right:0px;position:absolute;");
s.set("#hscroll .scroll", "height:16px;left:0px;bottom:0px;position:absolute;");
s.set("#panel #outline", "border:1px solid #000;background-color:#FFF;");
s.set("#panel #corner", "background-color:#D4D0C8;right:0px;bottom:0px;position:absolute;");
s.set("#panel #vscroll .vscroll", "");
s.set("#panel #hscroll .hscroll", "");
s.set("#edit .sdown", "background-color:#FFF;font-size:13px;");
s.set("#edit #outline", "border-top:1px solid #808080;border-left:1px solid #808080;");
s.set("#edit #inline", "border-top:1px solid #404040;border-left:1px solid #404040;");
s.set("#edit #text", "color:#000000;");
s.set("#edit #disabled #text", "color:#808080;");
s.set("#password .edit", "");
s.set("#checkbox .edit", "");
s.set("#checkbox #active", "background-color:#FFF;");
s.set("#checkbox #press", "background-color:#D4D0C8;");
s.set("#form .sup", "");
s.set("#form #inline", "padding:1px 2px 2px 1px;");
s.set("#form #title", "height:18px;background-image:url(" + wsclPath + "skins/windows/form.png);font-size:12px;color:#D4D0C8;");
s.set("#form #title #text", "padding-top:diff(3|2|1)px;padding-left:3px;");
s.set("#form #active #title", "background-image:url(" + wsclPath + "skins/windows/form_a.png);color:#FFF;");
s.set("#form #close .sup", "width:15px;height:14px;position:absolute;top:5px;right:6px;position:absolute;");
s.set("#form #close #active .sup", "");
s.set("#form #close #icon", "top:0;left:0;");
s.set("#form #close #press .sdown", "");
s.set("#form #close #press #icon", "top:1px;left:1px;");
s.set("#form #main", "");
s.set("#button .sup", "");
s.set("#button #disabled #text", "color:#808080");
s.set("#button #border", "background-image:none;margin:1px;padding:1px;");
s.set("#button #client", "background-color:#D4D0C8;");
s.set("#button #text", "cursor:default;top:diff(1|0|1)px;left:0px;text-align:center;font-size:12px;color:#000000;");
s.set("#button #active #outline", "border:1px solid #000;");
s.set("#button #active #inline", "border-top:1px solid #FFF;border-left:1px solid #FFF;border-right:1px solid #808080;border-bottom:1px solid #808080;");
s.set("#button #active #border", "background-image:url(" + wsclPath + "skins/windows/button.gif);");
s.set("#button #active #text", "top:diff(1|0|1)px;left:0px;");
s.set("#button #press .button #active", "");
s.set("#button #press #inline", "border-top:1px solid #808080;border-left:1px solid #808080;border-right:1px solid #FFF;border-bottom:1px solid #FFF;");
s.set("#button #press #text", "top:diff(2|1|2)px;left:1px;");
s.set("#select .edit", "");
s.set("#select #text #outline", "padding:1px;margin:1px;background-image:none;");
s.set("#select #text #inline", "cursor:default;padding-top:diff(1|0|1)px;background-color:#FFF;color:#000;");
s.set("#select #button .sup", "");
s.set("#select #button #outline", "border-top:1px solid #D4D0C8;border-left:1px solid #D4D0C8;border-right:1px solid #404040;border-bottom:1px solid #404040;");
s.set("#select #button #inline", "border-top:1px solid #FFF;border-left:1px solid #FFF;border-right:1px solid #808080;border-bottom:1px solid #808080;");
s.set("#select #button #icon", "top:0;left:0;");
s.set("#select #press #text .select #text", "");
s.set("#select #press #button #outline", "border-top:1px solid #808080;border-left:1px solid #808080;border-right:1px solid #808080;border-bottom:1px solid #808080;");
s.set("#select #press #button #inline", "border-top:1px solid #D4D0C8;border-left:1px solid #D4D0C8;border-right:1px solid #D4D0C8;border-bottom:1px solid #D4D0C8;");
s.set("#select #press #button #icon", "top:1px;left:1px;");
s.set("#select #active #text #outline", "background-image:url(" + wsclPath + "skins/windows/select.bmp);");
s.set("#select #active #text #inline", "background-color:#0A246A;color:#FFF;");
s.set("#select #options .panel", "");
s.set("#select #item", "font-size:13px;background-image:none;height:17px;");
s.set("#select #item #outline", "margin:1px;padding-top:diff(1|0|1)px;background-color:#FFF;color:#000;");
s.set("#select #item #over", "background-image:url(" + wsclPath + "skins/windows/select.bmp);");
s.set("#select #item #over #outline", "background-color:#0A246A;color:#FFF;");
s.set("#calendar .edit", "font-size:12px;");
s.set("#calendar #name", "font-weight:bold;");
s.set("#calendar #name #client", "width:22px;height:16px;cursor:default;background-color:#808080;");
s.set("#calendar #name #text", "position:absolute;top:diff(2|1|2)px;text-align:center;color:#D4D0C8;");
s.set("#calendar #date #inline", "padding:1px 4px;");
s.set("#calendar #date #client", "width:14px;height:14px;cursor:default;");
s.set("#calendar #date #text", "display:block;position:absolute;top:diff(-1|-1|-2)px;text-align:center;background-color:#FFF;color:#000;");
s.set("#calendar #date #link #text", "color:#000;");
s.set("#calendar #date #today #text", "background-color:#0A246A;color:#FFF;");
s.set("#calendar #date #blank #text", "display:none;");
s.set("#calendar #date #over #text", "background-color:#888;color:#FFF;");
s.set("#calendar #date #active #text", "color:#FF0000;");
s.set("#table .edit", "font-size:12px;");
s.set("#table #client", "background-color:#FFF;");
s.set("#table #vscroll .vscroll", "");
s.set("#table #hscroll .hscroll", "");
s.set("#table #corner .panel #corner", "");
s.set("#table #header #cell .sup", "height:17px;cursor:default;");
s.set("#table #header #cell #text", "text-align:center;");
s.set("#table #data #cell", "height:17px;cursor:default;background-color:transparent;");
s.set("#table #row", "background-color:transparent;");
s.set("#table #row #over", "background-color:#CCF;");
s.set("#table #icon", "left:4px;");
s.set("#progress .edit", "");
s.set("#progress #text", "background-color:#0A246A;color:#FFF;text-align:center;");
s.set("#menuitem", "height:24px;font-size:13px;background-color:#D4D0C8;color:#000;cursor:default;");
s.set("#menuitem #inline", "padding:5px 6px;");
s.set("#menuitem #text", "top:diff(1|0|0)px;");
s.set("#menuitem #icon", "right:4px;color:#000;");
s.set("#menuitem #over", "background-color:#0A246A;color:#FFF;");
s.set("#menuitem #over #icon", "color:#FFF;");
s.set("#popupmenu .sup", "");
s.set("#popupmenu #outline", "border-top:1px solid #D4D0C8;border-left:1px solid #D4D0C8;");
s.set("#popupmenu #inline", "border-top:1px solid #FFF;border-left:1px solid #FFF;");
s.set("#paletteform .form", "font-size:12px;width:526px;height:320px;");
s.set("#paletteform #palette", "top:8px;left:8px;position:absolute;width:256px;height:256px;background-image:url(" + wsclPath + "skins/windows/palette.png);");
s.set("#paletteform #lightbar", "top:5px;left:272px;position:absolute;width:30px;height:262px;");
s.set("#paletteform #basiccolors", "top:8px;left:312px;position:absolute;width:200px;height:20px;");
s.set("#paletteform #customcolors", "top:153px;left:312px;position:absolute;width:200px;height:20px;");
s.set("#paletteform #text", "height:20px;");
s.set("#paletteform #grid .edit", "background-color:transparent;");
s.set("#paletteform #grid #outline", "margin:3px 2px 2px 3px;");
s.set("#paletteform #grid #client", "width:16px;height:11px;");
s.set("#paletteform #grid #border", "width:26px;height:21px;position:absolute;");
s.set("#paletteform #grid #border #outline", "border:1px dotted #000;padding:1px;");
s.set("#paletteform #grid #border #inline", "border:1px solid #000;");
s.set("#paletteform #color .down", "top:200px;left:312px;width:60px;height:40px;position:absolute;");
s.set("#paletteform #color #edit .edit", "top:246px;left:312px;width:60px;height:18px;font-size:12px;position:absolute;");
s.set("#paletteform #color #edit #inline", "padding-left:2px;");
s.set("#paletteform #hue", "top:20diff(3|2|3)px;left:380px;width:37px;height:18px;font-size:12px;position:absolute;");
s.set("#paletteform #hue #text", "text-align:right;");
s.set("#paletteform #hue #edit .edit", "top:200px;left:420px;width:29px;height:18px;font-size:12px;position:absolute;");
s.set("#paletteform #hue #edit #inline", "padding-left:2px;");
s.set("#paletteform #saturation .paletteform #hue", "top:22diff(6|5|6)px;");
s.set("#paletteform #saturation #edit", "top:223px;");
s.set("#paletteform #light .paletteform #hue", "top:24diff(9|8|9)px;");
s.set("#paletteform #light #edit", "top:246px;");
s.set("#paletteform #red .paletteform #hue", "left:452px;width:26px;");
s.set("#paletteform #red #edit", "left:481px;");
s.set("#paletteform #green .paletteform #red", "top:22diff(6|5|6)px;");
s.set("#paletteform #green #edit", "top:223px;");
s.set("#paletteform #blue .paletteform #red", "top:24diff(9|8|9)px;");
s.set("#paletteform #blue #edit", "top:246px;");
s.set("#paletteform #apply .button", "top:269px;left:60px;width:60px;height:22px;position:absolute;");
s.set("#paletteform #cancel .paletteform #apply", "left:150px;");
s.set("#paletteform #addto .paletteform #apply", "width:140px;left:342px;");
s.set("#calendarform .form", "width:185px;height:185px;");
s.set("#calendarform #month .select", "left:9px;top:7px;width:70px;height:21px;position:absolute;");
s.set("#calendarform #year .edit", "left:85px;top:7px;width:65px;height:21px;position:absolute;");
s.set("#calendarform #year #up .sup", "left:153;top:8px;width:16px;height:8px;position:absolute;");
s.set("#calendarform #year #up #icon", "left:4px;top:1px;");
s.set("#calendarform #year #up #press .sdown", "");
s.set("#calendarform #year #up #press #icon", "left:5px;top:2px;");
s.set("#calendarform #year #down .calendarform #year #up", "top:18px;");
s.set("#calendarform #calendar .calendar", "left:9px;top:35px;position:absolute;");
s.set("#radio", "background-image:none;");
s.set("#radio #outline", "margin:1px;background-color:#D4D0C8;");
s.set("#radio #outdark", "color:#808080;");
s.set("#radio #outlight", "color:#FFF;");
s.set("#radio #indark", "color:#404040;");
s.set("#radio #inlight", "color:#D4D0C8;");
s.set("#radio #client", "color:#FFF;");
s.set("#radio #icon", "color:#000;");
s.set("#radio #active", "background-image:url(" + wsclPath + "skins/windows/button.gif);");
s.set("#treeview", "cursor:pointer;");
s.set("#treeview #title", "padding-left:12px;font-size:14px;background:none;color:green;");
s.set("#treeview #items", "padding-left:16px;");
s.set("#treeview #unfold #title", "background:url(" + wsclPath + "skins/windows/treefold.bmp) no-repeat left center;");
s.set("#treeview #fold #title", "background:url(" + wsclPath + "skins/windows/treeunfold.bmp) no-repeat left center;");
s.set("#level0 .treeview", "");
s.set("#level0 #title", "color:red;");
s.set("#level1 .treeview", "");
s.set("#level1 #title", "color:blue;");
